package it.giovanni.arkivio.utils

class Globals {

    companion object {

        var DATE = "DATE"
        var EMAIL = "EMAIL"
        var FONTS = "FONTS"
        var VOLLEY = "VOLLEY"
        var NEARBY = "NEARBY"
        var CARD_IO = "CARD_IO"
        var RETROFIT = "RETROFIT"
        var WEB_VIEW = "WEB_VIEW"
        var EXOPLAYER = "EXOPLAYER"
        var PREFERENCE = "PREFERENCE"
        var ASYNC_HTTP = "ASYNC_HTTP"
        var DATE_FORMAT = "DATE_FORMAT"
        var DATE_PICKER = "DATE_PICKER"
        var LANGUAGE_ID = "LANGUAGE_ID"
        var TRANSLATION = "TRANSLATION"
        var PERMISSIONS = "PERMISSIONS"
        var DIALOG_FLOW = "DIALOG_FLOW"
        var NEARBY_CHAT = "NEARBY_CHAT"
        var NEARBY_GAME = "NEARBY_GAME"
        var SMARTWORKING = "SMARTWORKING"
        var RUBRICA_LIST = "RUBRICA_LIST"
        var QUICK_ANSWER = "QUICK_ANSWER"
        var SEARCH_VIDEO = "SEARCH_VIDEO"
        var NOTIFICATION = "NOTIFICATION"
        var STICKY_HEADER = "STICKY_HEADER"
        var NEARBY_SEARCH = "NEARBY_SEARCH"
        var NEARBY_BEACONS = "NEARBY_BEACONS"
        var IMAGE_LABELING = "IMAGE_LABELING"
        var RUBRICA_DETAIL = "RUBRICA_DETAIL"
        var LAYOUT_MANAGER = "LAYOUT_MANAGER"
        var LOGCAT_PROJECTS = "LOGCAT_PROJECTS"
        var PREFERENCE_LIST = "PREFERENCE_LIST"
        var YOUTUBE_MANAGER = "YOUTUBE_MANAGER"
        var MACHINE_LEARNING = "MACHINE_LEARNING"
        var TEXT_RECOGNITION = "TEXT_RECOGNITION"
        var FACIAL_DETECTION = "FACIAL_DETECTION"
        var OBJECT_DETECTION = "OBJECT_DETECTION"
        var BARCODE_SCANNING = "BARCODE_SCANNING"
        var RUBRICA_REALTIME = "RUBRICA_REALTIME"
        var NOTIFICATION_HOME = "NOTIFICATION_HOME"
        var AUTOML_VISION_EDGE = "AUTOML_VISION_EDGE"
        var LANDMARKS_RECOGNITION = "LANDMARKS_RECOGNITION"
        var CALENDARVIEW_VERTICAL = "CALENDARVIEW_VERTICAL"
        var CALENDARVIEW_HORIZONTAL = "CALENDARVIEW_HORIZONTAL"

        // BACK INTENT KEY PARAMS
        var BACK_PARAM_KEY_USER_SEARCH = "BACK_PARAM_KEY_USER_SEARCH"
        var BACK_PARAM_KEY_USER_PREFERENCE = "BACK_PARAM_KEY_USER_PREFERENCE"

        // Request code
        var REQUEST_CODE_USER_PREFERENCE = 1001
        var REQUEST_CODE_EVENT_USER_SEARCH = 1002
    }
}