package it.giovanni.arkivio.utils

class Globals {

    companion object {

        var LOGCAT_PROJECTS = "LOGCAT_PROJECTS"

        var DATE = "DATE"
        var DATE_FORMAT = "DATE_FORMAT"
        var DATE_PICKER = "DATE_PICKER"
        var CALENDARVIEW_HORIZONTAL = "CALENDARVIEW_HORIZONTAL"
        var CALENDARVIEW_VERTICAL = "CALENDARVIEW_VERTICAL"
        var SMARTWORKING = "SMARTWORKING"

        var RUBRICA_HOME = "RUBRICA_HOME"
        var RUBRICA_LIST = "RUBRICA_LIST"
        var RUBRICA_DETAIL = "RUBRICA_DETAIL"
        var WEB_VIEW = "WEB_VIEW"
        var GC3_WEB_VIEW = "GC3_WEB_VIEW"
        var PERMISSIONS = "PERMISSIONS"
        var LAYOUT_MANAGER = "LAYOUT_MANAGER"
        var DIALOG_FLOW = "DIALOG_FLOW"
        var PREFERENCE = "PREFERENCE"
        var PREFERENCE_LIST = "PREFERENCE_LIST"
        var STICKY_HEADER = "STICKY_HEADER"
        var CARD_IO = "CARD_IO"
        var YOUTUBE_MANAGER = "YOUTUBE_MANAGER"
        var SEARCH_VIDEO = "SEARCH_VIDEO"
        var FONTS = "FONTS"
        var NOTIFICATION = "NOTIFICATION"
        var NEARBY = "NEARBY"
        var NEARBY_SEARCH = "NEARBY_SEARCH"
        var NEARBY_CHAT = "NEARBY_CHAT"
        var NEARBY_GAME = "NEARBY_GAME"
        var NEARBY_BEACONS = "NEARBY_BEACONS"
        var MACHINE_LEARNING = "MACHINE_LEARNING"
        var TEXT_RECOGNITION = "TEXT_RECOGNITION"
        var IMAGE_LABELING = "IMAGE_LABELING"
        var FACIAL_DETECTION = "FACIAL_DETECTION"
        var OBJECT_DETECTION = "OBJECT_DETECTION"
        var BARCODE_SCANNING = "BARCODE_SCANNING"
        var LANGUAGE_ID = "LANGUAGE_ID"
        var TRANSLATION = "TRANSLATION"
        var QUICK_ANSWER = "QUICK_ANSWER"
        var AUTOML_VISION_EDGE = "AUTOML_VISION_EDGE"
        var LANDMARKS_RECOGNITION = "LANDMARKS_RECOGNITION"

        // BACK INTENT KEY PARAMS
        var BACK_PARAM_KEY_EMPLOYEE_SEARCH = "BACK_PARAM_KEY_EMPLOYEE_SEARCH"
        var BACK_PARAM_KEY_USER_PREFERENCE = "BACK_PARAM_KEY_USER_PREFERENCE"

        // Request code
        var REQUEST_CODE_EVENT_HOME = 1000
        var REQUEST_CODE_USER_PREFERENCE = 1001
        var REQUEST_CODE_EVENT_WORKING_AREA = 1002
        var REQUEST_CODE_EVENT_EMPLOYEE_SEARCH = 1003
    }
}