package it.giovanni.arkivio.utils

class Globals {

    companion object {

        var DATE = "DATE"
        var EMAIL = "EMAIL"
        var FONTS = "FONTS"
        var VOLLEY = "VOLLEY"
        var CARD_IO = "CARD_IO"
        var WEB_VIEW = "WEB_VIEW"
        var EXOPLAYER = "EXOPLAYER"
        var PREFERENCE = "PREFERENCE"
        var ASYNC_HTTP = "ASYNC_HTTP"
        var DATE_FORMAT = "DATE_FORMAT"
        var DATE_PICKER = "DATE_PICKER"
        var PERMISSIONS = "PERMISSIONS"
        var DIALOG_FLOW = "DIALOG_FLOW"
        var SMARTWORKING = "SMARTWORKING"
        var RUBRICA_LIST = "RUBRICA_LIST"
        var NOTIFICATION = "NOTIFICATION"
        var STICKY_HEADER = "STICKY_HEADER"
        var RUBRICA_DETAIL = "RUBRICA_DETAIL"
        var LAYOUT_MANAGER = "LAYOUT_MANAGER"
        var LOGCAT_PROJECTS = "LOGCAT_PROJECTS"
        var PREFERENCE_LIST = "PREFERENCE_LIST"
        var SIMPLE_RETROFIT = "SIMPLE_RETROFIT"
        var MACHINE_LEARNING = "MACHINE_LEARNING"
        var TEXT_RECOGNITION = "TEXT_RECOGNITION"
        var FACIAL_DETECTION = "FACIAL_DETECTION"
        var RUBRICA_REALTIME = "RUBRICA_REALTIME"
        var NOTIFICATION_HOME = "NOTIFICATION_HOME"
        var CALENDARVIEW_VERTICAL = "CALENDARVIEW_VERTICAL"
        var CALENDARVIEW_HORIZONTAL = "CALENDARVIEW_HORIZONTAL"

        // PUNTONET
        var PUNTONET = "PUNTONET"
        var MVVM_USER_INPUT = "MVVM_USER_INPUT"
        var MVVM_LOGIN_RESULT = "MVVM_LOGIN_RESULT"
        var MVVM_LOGIN = "MVVM_LOGIN"
        var MVVM_USERS = "MVVM_USERS"
        var COROUTINE_BASICS = "COROUTINE_BASICS"
        var COROUTINE_SCOPES = "COROUTINE_SCOPES"
        var COROUTINE_JOBS_CANCELLATION = "COROUTINE_JOBS_CANCELLATION"
        var COROUTINE_RUN_BLOCKING = "COROUTINE_RUN_BLOCKING"
        var COROUTINE_VALUES = "COROUTINE_VALUES"
        var COROUTINE_CHANNELS = "COROUTINE_CHANNELS"
        var NBA_RETROFIT = "NBA_RETROFIT"
        var GET_POST = "GET_POST"
        var POST = "POST"
        var PAGING = "PAGING"

        // BACK INTENT KEY PARAMS
        var BACK_PARAM_KEY_USER_SEARCH = "BACK_PARAM_KEY_USER_SEARCH"
        var BACK_PARAM_KEY_USER_PREFERENCE = "BACK_PARAM_KEY_USER_PREFERENCE"

        // Request code
        var REQUEST_CODE_USER_PREFERENCE = 1001
        var REQUEST_CODE_EVENT_USER_SEARCH = 1002
    }
}